(deftemplate a (slot sa))
(deftemplate b (slot sb))
(deftemplate c (slot sc))
(deftemplate d (slot sd))
(deftemplate e (slot se))
(deftemplate f (slot sf))
(deftemplate g (slot sg))
(deftemplate h (slot sh))
