(defclass A (is-a USER) (slot sa))
(defclass B (is-a USER) (slot sb))
(defclass C (is-a USER) (slot sc))
(defclass D (is-a USER) (slot sd))
(defclass E (is-a USER) (slot se))
(defclass F (is-a USER) (slot sf))
(defclass G (is-a USER) (slot sg))
(defclass H (is-a USER) (slot sh))
