(deftemplate a (multislot sa))
(deftemplate b (slot sb))
(deftemplate c (multislot sc))
(deftemplate d (slot sd))
(deftemplate e (multislot se))
(deftemplate f (slot sf))
(deftemplate g (multislot sg))
(deftemplate h (slot sh))
